spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kdy
    username: root
    password: ehd5765613
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework:
        boot: DEBUG