spring:

  datasource:
    #url: jdbc:mysql://localhost:3306/kdy
    url: jdbc:mysql://database-2.ch31jk6kzgqo.ap-northeast-2.rds.amazonaws.com/kdy?characterEncoding=utf8
    username: admin
    password: ehd5765613
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org:
      springframework:
        boot: DEBUG