spring:

  logging:
    level:
      org:
        springframework:
          boot: debug

  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  data:
    redis:
      host: localhost
#      host: menteetor.site
      port: 6379

  jwt:
    secret: 795a494eb4ca40d62227cc695a41e69d1e13fa5da2263727c28ba073fdbdd2f2

  datasource:
  
    #    kdy
   url: jdbc:mysql://kdy.ch31jk6kzgqo.ap-northeast-2.rds.amazonaws.com/kdy?characterEncoding=utf8
   username : admin
    #url: jdbc:mysql://localhost:3306/kdy
    #username: root
   password: ehd5765613

    #    JHL
    # url: jdbc:mysql://localhost:3306/member
    # username: root
    # password: asd990810
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: rjQ2Uiy66PcURd4QPXcI
            client-secret: i2xP6gkaDA

            # 로그인 성공 시, 클라이언트가 이동하는 uri
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_cod e
            scope:
              - id
              - name
              - email
              - gender
              - mobile
            client-name: Naver

          kakao:
            client-id: 4d9fdae799c6a1b6ea62ce9800ade65b
            client-secret: ISExtaymvbuqOMPxm8MkdzokvFmGQInw

            # 로그인 성공 시, 클라이언트가 이동하는 uri
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao

        provider:
          naver:
            # 네이버 로그인 연동 URL 생성
            authorization-uri: https://nid.naver.com/oauth2.0/authorize

            # 접근 토큰 발급 요청
            token-uri: https://nid.naver.com/oauth2.0/token

            # 접근 토큰 이용하여 프로필 API 호출
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            # 카카오 로그인 연동 URL 생성
            authorization-uri: https://kauth.kakao.com/oauth/authorize

            # 접근 토큰 발급 요청
            token-uri: https://kauth.kakao.com/oauth/token

            # 접근 토큰 이용하여 프로필 API 호출
            user-info-uri: https://kapi.kakao.com/v2/user/me

api:
  univcert:
    #    key: ce6dc2f8-3d83-44ca-923a-7143022e5f3d
    key: fc3b5c45-85eb-4fd6-8309-a5725170a2c8

cloud:
  aws:
    s3:
      bucket: five-image
      bucket_image: fiveidiots-image
      bucket_video: fiveidiots-video
      bucket_pdf: fiveidiots-pdf
    credentials:
      access-key: AKIAXYAFCWJQBQ46DBPJ
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

