name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        env:
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
          DATASOURCE_USERNAME: ${{ secrets.DATASOURCE_USERNAME }}
          DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
          UNIVCERT_KEY: ${{ secrets.UNIVCERT_KEY }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
          FIREBASE_CONFIG_PATH: ${{ secrets.FIREBASE_CONFIG_PATH }}
          FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
        run: ./gradlew build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker build & push to Docker hub
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64/v8 --push --tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest .

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
            docker stop $(docker ps -a -q) || true
            docker rm $(docker ps -a -q) || true
            docker run -d \
              --log-driver=syslog \
              -p 8080:8080 \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e spring.data.redis.host=${{ secrets.REDIS_HOST }} \
              -e spring.data.redis.port=${{ secrets.REDIS_PORT }} \
              -e spring.jwt.secret=${{ secrets.JWT_SECRET }} \
              -e spring.datasource.url=${{ secrets.DATASOURCE_URL }} \
              -e spring.datasource.username=${{ secrets.DATASOURCE_USERNAME }} \
              -e spring.datasource.password=${{ secrets.DATASOURCE_PASSWORD }} \
              -e naver.client.id=${{ secrets.NAVER_CLIENT_ID }} \
              -e naver.client.secret=${{ secrets.NAVER_CLIENT_SECRET }} \
              -e kakao.client.id=${{ secrets.KAKAO_CLIENT_ID }} \
              -e kakao.client.secret=${{ secrets.KAKAO_CLIENT_SECRET }} \
              -e api.univcert.key=${{ secrets.UNIVCERT_KEY }} \
              -e aws.access.key=${{ secrets.AWS_S3_ACCESS_KEY }} \
              -e aws.secret.key=${{ secrets.AWS_S3_SECRET_KEY }} \
              -e firebase.config-path=${{ secrets.FIREBASE_CONFIG_PATH }} \
              -e firebase.url=${{ secrets.FIREBASE_URL }} \
              ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest      
            docker image prune -a -f || true

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Generate and submit dependency graph
        uses: gradle/gradle-build-action@v2
